config/routes.rb
SignApp::Application.routes.draw do
  resources :applicant_fields

  resources :credits

  resources :applicants

  resources :form_fields

  resources :options

  resources :field_types

  resources :fields

  resources :forms

  resources :banks

  match 'forms/:form_id/applicant/:applicant_id' => "forms#setup"
  match 'download/:form_id/applicant/:applicant_id(.:format)' => "forms#download"
  post  'position' => "form_fields#position", :as => 'position'

  root :to => 'forms#index'

end

app/models/applicant_field.rb
class ApplicantField < ActiveRecord::Base
  attr_accessible :applicant_id, :field_id, :value

  belongs_to :applicant
  belongs_to :field
end

app/controllers/applicant_fields_controller.rb
class ApplicantFieldsController < ApplicationController
  # GET /applicant_fields
  # GET /applicant_fields.json
  def index
    @applicant_fields = ApplicantField.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applicant_fields }
    end
  end

  # GET /applicant_fields/1
  # GET /applicant_fields/1.json
  def show
    @applicant_field = ApplicantField.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @applicant_field }
    end
  end

  # GET /applicant_fields/new
  # GET /applicant_fields/new.json
  def new
    @applicant_field = ApplicantField.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @applicant_field }
    end
  end

  # GET /applicant_fields/1/edit
  def edit
    @applicant_field = ApplicantField.find(params[:id])
  end

  # POST /applicant_fields
  # POST /applicant_fields.json
  def create
    @applicant_field = ApplicantField.new(params[:applicant_field])

    respond_to do |format|
      if @applicant_field.save
        format.html { redirect_to @applicant_field, notice: 'Applicant field was successfully created.' }
        format.json { render json: @applicant_field, status: :created, location: @applicant_field }
      else
        format.html { render action: "new" }
        format.json { render json: @applicant_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applicant_fields/1
  # PUT /applicant_fields/1.json
  def update
    @applicant_field = ApplicantField.find(params[:id])

    respond_to do |format|
      if @applicant_field.update_attributes(params[:applicant_field])
        format.html { redirect_to @applicant_field, notice: 'Applicant field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @applicant_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicant_fields/1
  # DELETE /applicant_fields/1.json
  def destroy
    @applicant_field = ApplicantField.find(params[:id])
    @applicant_field.destroy

    respond_to do |format|
      format.html { redirect_to applicant_fields_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/applicant_fields_helper.rb
module ApplicantFieldsHelper
end

app/views/applicant_fields/_form.html.erb
<%= form_for(@applicant_field) do |f| %>
  <% if @applicant_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applicant_field.errors.count, "error") %> prohibited this applicant_field from being saved:</h2>

      <ul>
      <% @applicant_field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :applicant_id %><br />
    <%= f.number_field :applicant_id %>
  </div>
  <div class="field">
    <%= f.label :field_id %><br />
    <%= f.number_field :field_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applicant_fields/edit.html.erb
<h1>Editing applicant_field</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant_field %> |
<%= link_to 'Back', applicant_fields_path %>

app/views/applicant_fields/index.html.erb
<h1>Listing applicant_fields</h1>

<table>
  <tr>
    <th>Applicant</th>
    <th>Field</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applicant_fields.each do |applicant_field| %>
  <tr>
    <td><%= applicant_field.applicant_id %></td>
    <td><%= applicant_field.field_id %></td>
    <td><%= applicant_field.value %></td>
    <td><%= link_to 'Show', applicant_field %></td>
    <td><%= link_to 'Edit', edit_applicant_field_path(applicant_field) %></td>
    <td><%= link_to 'Destroy', applicant_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Applicant field', new_applicant_field_path %>

app/views/applicant_fields/new.html.erb
<h1>New applicant_field</h1>

<%= render 'form' %>

<%= link_to 'Back', applicant_fields_path %>

app/views/applicant_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Applicant:</b>
  <%= @applicant_field.applicant_id %>
</p>

<p>
  <b>Field:</b>
  <%= @applicant_field.field_id %>
</p>

<p>
  <b>Value:</b>
  <%= @applicant_field.value %>
</p>


<%= link_to 'Edit', edit_applicant_field_path(@applicant_field) %> |
<%= link_to 'Back', applicant_fields_path %>