config/routes.rb
SignApp::Application.routes.draw do
  resources :applicant_fields

  resources :credits

  resources :applicants

  resources :form_fields

  resources :options

  resources :field_types

  resources :fields

  resources :forms

  resources :banks

  match 'forms/:form_id/applicant/:applicant_id' => "forms#setup"
  match 'download/:form_id/applicant/:applicant_id(.:format)' => "forms#download"
  post  'position' => "form_fields#position", :as => 'position'

  root :to => 'forms#index'

end

app/controllers/field_types_controller.rb
class FieldTypesController < ApplicationController
  # GET /field_types
  # GET /field_types.json
  def index
    @field_types = FieldType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @field_types }
    end
  end

  # GET /field_types/1
  # GET /field_types/1.json
  def show
    @field_type = FieldType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @field_type }
    end
  end

  # GET /field_types/new
  # GET /field_types/new.json
  def new
    @field_type = FieldType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @field_type }
    end
  end

  # GET /field_types/1/edit
  def edit
    @field_type = FieldType.find(params[:id])
  end

  # POST /field_types
  # POST /field_types.json
  def create
    @field_type = FieldType.new(params[:field_type])

    respond_to do |format|
      if @field_type.save
        format.html { redirect_to @field_type, notice: 'Field type was successfully created.' }
        format.json { render json: @field_type, status: :created, location: @field_type }
      else
        format.html { render action: "new" }
        format.json { render json: @field_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /field_types/1
  # PUT /field_types/1.json
  def update
    @field_type = FieldType.find(params[:id])

    respond_to do |format|
      if @field_type.update_attributes(params[:field_type])
        format.html { redirect_to @field_type, notice: 'Field type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @field_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /field_types/1
  # DELETE /field_types/1.json
  def destroy
    @field_type = FieldType.find(params[:id])
    @field_type.destroy

    respond_to do |format|
      format.html { redirect_to field_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/field_types_helper.rb
module FieldTypesHelper
end

app/views/field_types/_form.html.erb
<%= form_for(@field_type) do |f| %>
  <% if @field_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field_type.errors.count, "error") %> prohibited this field_type from being saved:</h2>

      <ul>
      <% @field_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/field_types/edit.html.erb
<h1>Editing field_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @field_type %> |
<%= link_to 'Back', field_types_path %>

app/views/field_types/index.html.erb
<h1>Listing field_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @field_types.each do |field_type| %>
  <tr>
    <td><%= field_type.name %></td>
    <td><%= link_to 'Show', field_type %></td>
    <td><%= link_to 'Edit', edit_field_type_path(field_type) %></td>
    <td><%= link_to 'Destroy', field_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Field type', new_field_type_path %>

app/views/field_types/new.html.erb
<h1>New field_type</h1>

<%= render 'form' %>

<%= link_to 'Back', field_types_path %>

app/views/field_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @field_type.name %>
</p>


<%= link_to 'Edit', edit_field_type_path(@field_type) %> |
<%= link_to 'Back', field_types_path %>