config/routes.rb
SignApp::Application.routes.draw do
  resources :applicant_fields

  resources :credits

  resources :applicants

  resources :form_fields

  resources :options

  resources :field_types

  resources :fields

  resources :forms

  resources :banks

  match 'forms/:form_id/applicant/:applicant_id' => "forms#setup"
  match 'download/:form_id/applicant/:applicant_id(.:format)' => "forms#download"
  post  'position' => "form_fields#position", :as => 'position'

  root :to => 'forms#index'

end

app/models/field.rb
class Field < ActiveRecord::Base
  attr_accessible :field_type_id, :name

  belongs_to :field_type

  has_many :form_fields
  has_many :forms, through: :form_fields

  has_many :applicant_fields
  has_many :applicants, through: :applicant_fields
end

app/models/field_type.rb
class FieldType < ActiveRecord::Base
  attr_accessible :name
  has_many :fields
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fields }
    end
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
    @field = Field.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @field }
    end
  end

  # GET /fields/new
  # GET /fields/new.json
  def new
    @field = Field.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @field }
    end
  end

  # GET /fields/1/edit
  def edit
    @field = Field.find(params[:id])
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(params[:field])

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render json: @field, status: :created, location: @field }
      else
        format.html { render action: "new" }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fields/1
  # PUT /fields/1.json
  def update
    @field = Field.find(params[:id])

    respond_to do |format|
      if @field.update_attributes(params[:field])
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field = Field.find(params[:id])
    @field.destroy

    respond_to do |format|
      format.html { redirect_to fields_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
  <% if @field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :field_type_id %><br />
    <%= f.number_field :field_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<h1>Listing fields</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Field type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fields.each do |field| %>
  <tr>
    <td><%= field.name %></td>
    <td><%= field.field_type_id %></td>
    <td><%= link_to 'Show', field %></td>
    <td><%= link_to 'Edit', edit_field_path(field) %></td>
    <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<h1>New field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @field.name %>
</p>

<p>
  <b>Field type:</b>
  <%= @field.field_type_id %>
</p>


<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>